### ISSUE TITLE
This extension breaks the reproduceable compilation of templates

### ISSUE THREAD

**Issue by stof** [yceruto/twigxray#2]
The hash is generated as `md5(spl_object_hash($node))`, which means that the compilation of templates won't be reproduceable, while Twig worked hard to move to reproduceable compilations.

**Comment by yceruto** [comment]
I agree, I'd like to build it from the template path but I can't figure out how to do that without a reflection object for access to the private `$source->getPath()`, do you have a better idea? 

I'd also like to expose the template path rather than its name only.

**Comment by yceruto** [comment]
See #4
